name: Deploy Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      environment_name: staging
    secrets: inherit
